sudo: required
dist: trusty

language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
#  - development
#  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - haxelib install tink_runloop
  - haxelib install tink_tcp
  - haxelib install travix
  - haxelib run travix install

script:
  #- haxelib run travix interp
  #- haxelib run travix php
  - haxelib run travix node
  - haxelib run travix neko -lib tink_tcp -lib tink_runloop -D concurrent
  - haxelib run travix neko -lib tink_tcp -lib tink_runloop
  - haxelib run travix neko -D nekotools
  - haxelib run travix neko -D mod_neko
  
  #- haxelib run travix python
  #- haxelib run travix flash
  #- haxelib run travix java -lib tink_tcp -lib tink_runloop
  #- haxelib run travix cpp -lib tink_tcp -lib tink_runloop
  #- haxelib run travix cs
